sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t adonyspg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adonyspg/docker-react yarn test
